### ISSUE TITLE
Not working anymore due to hltb changes

### ISSUE THREAD

**Issue by sneakingJ** [ivankayzer/howlongtobeat#3]
Hey, I see you have not worked on this project for a while but hltb seemed to have changed something very recently and requests are failing now. Any chance on fixing it?

Your work on this is appreciated <3

**Comment by ivankaizer** [comment]
Hey,

Thank you for your feedback 😊

should be fixed now, run `composer update`

**Comment by sneakingJ** [comment]
Can confirm, it works now.
Thank you :)
