### ISSUE TITLE
API stopped working

### ISSUE THREAD

**Issue by sallaboy** [ivankayzer/howlongtobeat#5]
Hi,

Thanks for the great Lib but since today or maybe several days back - it stopped working.
Maybe HLTB changed the url of the query page ?

Dmitry

**Comment by sneakingJ** [comment]
Yep. Nothing is working anymore.
Hopefully this can be fixed :pray:

**Comment by sneakingJ** [comment]
Maybe this issue from another repo helps: https://github.com/ckatzorke/howlongtobeat/issues/40

**Comment by ivankaizer** [comment]
Should be fixed with latest release
